//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularKendo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Table
    {
        public decimal EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> EmployeeSalary { get; set; }
        public string Email { get; set; }
        public Nullable<int> EmployeeAge { get; set; }
    }
}
